### ISSUE TITLE
MIME nosniff

### ISSUE THREAD

**Issue by ps-logic** [fewieden/MMM-Fuel#11]
Thanks for sharing this great module.

Unfortunatally I'm getting a MIME error saying "X-Content-Type-Options: nosniff".
Anyone there who can help me?

Thanks guys!

**Comment by fewieden** [comment]
will check it the next days. do you have any logs or more details to provide?

**Comment by fewieden** [comment]
Can't reproduce this error with my config. Can you send me your config on the forum?

**Comment by Softyathome** [comment]
Thanks for your module.
I hope, my wife will see the possibility to save money :-)
But before i can show her the new module i need a little help.
I just get "Lade ..." on my mirror. Do you have an idea why?
Maybe the "request" missing? How can i check this?
Thanks

**Comment by fewieden** [comment]
Does your issue still persist?
