### ISSUE TITLE
MMM-Fuel / Gasbuddy - Gas Prices Not Correctly Sorted

### ISSUE THREAD

**Issue by butchkemper** [fewieden/MMM-Fuel#110]
Platform (Hardware/OS): Raspberry Pi Model 3 A+

Node version: 

MagicMirror² version: v2.23.0

Module version: MMM-Fuel 2.4.0

Description of the issue:

Prices do not sort into correct descending order: entry 5 is more than entry 1, entry 6 is more than entry 2, and entry 7 is equal to entry 2.  Please see attached graphic.

Config data is:
               {
                        module: "MMM-Fuel",
                        position: "top_right",
                        config: {
                                provider: "gasbuddy",
                                zip: "75048",
                                types: ["regular"],
                                sortby: "regular",
                                max: 7,
                                showDistance: false,
                                fade: false,
                                updateinterval: 30000,
                                rotate: false,
                                rotateInterval: 15000
                                }
                },

![MMM-Fuel-Gasbuddy](https://github.com/fewieden/MMM-Fuel/assets/43898632/8872b972-6083-4a36-991f-c743d177612c)

**Comment by butchkemper** [comment]
An update to this issue.

I observed sometimes the last fuel price entries which were not sorted correctly would display as >$2.99.  The Gas Buddy and webpage application showed price for that station as "---" (without the quotes).  I think that means "price not reported". 

When the price is "---", the MMM-Fuel data gathering process inserts the price from the previous station and places a ">" before the price amount.

It appears there are two issues with the Gasbuddy routines: 1) items are not correctly sorted; 2) items with "price not provided" are incorrectly displayed.

**Comment by butchkemper** [comment]
Update #2 

I found the place where missing prices are handled apis/utils/index.js so everything is working as designed.  Please excuse that ring.   

Butch

**Comment by butchkemper** [comment]
Updated original comment for updateinterval = 30000 instead of 30.

**Comment by fewieden** [comment]
@butchkemper first of all thank you for your donation, much appreciated. I have not received notifications for your issue and only saw it after looking into your Github profile.

Looking at your config I can spot two issues caused by the wrong letter casing. It should be camel-cased like this:
```js
updateInterval: 30000,
sortBy: "regular",
```
![image](https://github.com/fewieden/MMM-Fuel/assets/9334168/253cd429-e99f-40bb-b398-72086362439a)

There is a fallback mechanism if there is a wrong value, so it still used `regular` for the sorting.

The sorting is indeed broken. I created a fix on the develop branch. You can test it with the following commands until I release a new version on the master branch:
```bash
cd ~/MagicMirror/modules/MMM-Fuel
git checkout develop
git pull
npm i --production
```

**Comment by butchkemper** [comment]
Thank you for the response.  Here are the results from doing the commands you suggested:

pi@MagicMirror:~/MagicMirror/modules/MMM-Fuel $ git checkout develop
M       package-lock.json
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
Switched to a new branch 'develop'
pi@MagicMirror:~/MagicMirror/modules/MMM-Fuel $ git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
From https://github.com/fewieden/MMM-Fuel
   d416546..eb32037  develop    -> origin/develop
Updating d416546..eb32037
error: Your local changes to the following files would be overwritten by merge:
        package-lock.json
Please commit your changes or stash them before you merge.
Aborting

I am totally new to git so I need you help to know what to do.

Thanks.

Butch

**Comment by fewieden** [comment]
@butchkemper there are modifications on your machine for the file `package-lock.json`.

You can revert that file with `git checkout package-lock.json`.

**Comment by butchkemper** [comment]
@fewieden Thank you for the help.  MMM-Fuel with Gasbuddy is working and the sort problem is corrected.
