### ISSUE TITLE
MMM-Fuel / Gasbuddy - Option to Sort Prices in Ascending Order

### ISSUE THREAD

**Issue by butchkemper** [fewieden/MMM-Fuel#111]
Platform (Hardware/OS): Raspberry Pi Model 3 A+

Node version:

MagicMirror² version: v2.23.0

Module version: 2.4.0

Description of the issue:

The prices are sorted in descending order (highest to lowest).  I want to see which station has the lowest prices so an option to sort in ascending order would be helpful.

Suggested implementation would a config variable "sortByAscend: true" or "sortAscend: true" would cause prices to be sorted in ascending order.  The default would be "false" and would cause prices to be sorted in descending order as is the current method.

**Comment by fewieden** [comment]
@butchkemper they should be sorted ascending already, without the bug described in [here](https://github.com/fewieden/MMM-Fuel/issues/110#issuecomment-1627791485).
