### ISSUE TITLE
Gasbuddy throws an exception and shows "Loading..." all the time

### ISSUE THREAD

**Issue by dyeatman** [fewieden/MMM-Fuel#115]
Platform (Hardware/OS): Raspberry Pi 3A

Node version:  18.18.0

MagicMirror² version: 2.25.0

Module version: 2.4.0

Description of the issue: Gasbuddy throws an exception and shows "Loading..." all the time.  All other modules work normally..

Logs from startup
[10.10.2023 21:37.46.237] [ERROR] (node:1898) UnhandledPromiseRejectionWarning: Error: Cannot find module 'node-fetch'
0|mm       | Require stack:
0|mm       | - /home/pi/MagicMirror/modules/MMM-Fuel/apis/tankerkoenig.js
0|mm       | - /home/pi/MagicMirror/modules/MMM-Fuel/node_helper.js
0|mm       | - /home/pi/MagicMirror/js/app.js
0|mm       | - /home/pi/MagicMirror/js/electron.js
0|mm       | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|mm       | -
0|mm       |     at node:internal/modules/cjs/loader:1084:15
0|mm       |     at Function.<anonymous> (node:electron/js2c/browser_init:2:117419)
0|mm       |     at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
0|mm       |     at node:internal/modules/cjs/loader:929:27
0|mm       |     at Function._load (node:electron/js2c/asar_bundle:2:13327)
0|mm       |     at Module.require (node:internal/modules/cjs/loader:1150:19)
0|mm       |     at require (node:internal/modules/cjs/helpers:110:18)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Fuel/apis/tankerkoenig.js:14:15)
0|mm       |     at Module._compile (node:internal/modules/cjs/loader:1271:14)
0|mm       |     at Object..js (node:internal/modules/cjs/loader:1326:10)
0|mm       |     at Module.load (node:internal/modules/cjs/loader:1126:32)
0|mm       |     at node:internal/modules/cjs/loader:967:12
0|mm       |     at Function._load (node:electron/js2c/asar_bundle:2:13327)
0|mm       |     at Module.require (node:internal/modules/cjs/loader:1150:19)
0|mm       |     at require (node:internal/modules/cjs/helpers:110:18)
0|mm       |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Fuel/node_helper.js:84:39)
0|mm       | (Use `electron --trace-warnings ...` to show where the warning was created)
0|mm       | [10.10.2023 21:37.46.238] [ERROR] (node:1898) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**** Config.js Entry
//
               {
                       module: "MMM-Fuel",
                       position: "top_left",
                       provider: "gasbuddy",
                       config: {
                             types: ["e85"],
                             zip: "73071",
                             max: 15
                       }
                },
//

**Comment by fewieden** [comment]
@dyeatman you specified the provider outside of the config object. You can see in the error message that it tries to use the default provider tankerkoenig.

Try the following config instead:
```js
{
	module: "MMM-Fuel",
	position: "top_left",
	config: {
		provider: "gasbuddy",
		types: ["e85"],
		zip: "73071",
		max: 15
	}
},
```

![image](https://github.com/fewieden/MMM-Fuel/assets/9334168/92bfdc8a-7bb5-46a6-b41e-fd9856a5aa67)

Also, it seems like you are missing the dependency `node-fetch` which caused the error. Make sure you follow the installation instructions in the README file to install the dependencies. https://github.com/fewieden/MMM-Fuel#installation

**Comment by dyeatman** [comment]
I had to rerun the npm I –production command again and the move of the provider line fixed it!

Really stupid on my part after looking at it an entire afternoon!

 

Thank you!

 

Dave
