### ISSUE TITLE
Not displaying service stations or prices just the header

### ISSUE THREAD

**Issue by Ray94520** [fewieden/MMM-Fuel#119]
Platform (Hardware/OS):

Node version:

MagicMirror² version:

Module version:

Description of the issue:
I've been using this on my magicmirror for several years now
and now all of a sudden it only displays the header names
it doesn't display the service stations or prices

I am located in the United States so therefore I'm using this code

`{
			module: "MMM-Fuel",
			position: "top_left",
			config: {
				provider: "autoblog",
				zip: "94596",
				types: ["regular", "mid-grade"],
				sortBy: "mid-grade",
				max: 4,
				shortenText: 29,
				showDistance: false,
				fade: false,
				rotateInterval: 600000,             // every 10 minutes
				updateInterval: 15 * 60 * 1000      // every 15 minutes
				// all your config options, which are different than their default values
			}
		},
`

I have just been told by the people at magicmirror that autoblog is not supported anymore is that true and if so what are my options

**Comment by fewieden** [comment]
@Ray94520 seems like the have been bought by another company https://www.thetruthaboutcars.com/cars/news-blog/the-current-version-of-autoblog-goes-dark-later-this-week-44509204

Did you try the gasbuddy provider?

**Comment by Ray94520** [comment]
No I did not but I will certainly give it a try I didn't know we could do
that

**Comment by Ray94520** [comment]
That actually worked perfectly
I did have to do a small change in types but that was no big deal
I'm back up and running
thank you for the quick response
