### ISSUE TITLE
MMM-Fuel shows no Prices.

### ISSUE THREAD

**Issue by xIExodusIx** [fewieden/MMM-Fuel#120]
Platform (Hardware/OS): Raspberri Pi 4 8GB, Raspi OS Bookworm 64bit

Node version: 20.09.0

MagicMirror² version: 2.29

Module version: ? 

Description of the issue: It runs, but only shows gas stations, the addresses and the distance, but not the gasoline prices.

**Comment by dathbe** [comment]
Are you using Autoblog?  From what I can tell, they've removed (fingers crossed, moved) their gas prices.

**Comment by xIExodusIx** [comment]
Hello,
no I'm using "Tankerkoenig", I'm from Germany and have an API-Key for "Tankerkönig" since MM 2.16. With MM 2.16 it worked very well. Then I had a long break (longtime illness) with MM and now I'm trying to setup it again.

**Comment by xIExodusIx** [comment]
My Mistake, I toke "E5" instead of "e5". Corrected it and now it works, prices are now displayed.
