### ISSUE TITLE
Module is not loading

### ISSUE THREAD

**Issue by fewieden** [fewieden/MMM-Fuel#15]
I created a new issue, as it doesn't belong to the one you commented on.

@Softyathome
> Thanks for your module.
> I hope, my wife will see the possibility to save money :-)
> But before i can show her the new module i need a little help.
> I just get "Lade ..." on my mirror. Do you have an idea why?
> Maybe the "request" missing? How can i check this?
> Thanks

**Comment by fewieden** [comment]
Did you follow the install instructions? To install the dependencies go to the module directory
```cd ~/MagicMirror/modules/MMM-Fuel``` then install them ```npm install --productive```.

Any errors in the electron or browser console, errors in the terminal or pm2 logs?

**Comment by Softyathome** [comment]
Yes, npm install --productive runs without errors.

But in the meantime i did a system update and it seems that the error is gone.
Thanks for your help.
