### ISSUE TITLE
No fuel data sine 2016-09-22

### ISSUE THREAD

**Issue by der-test** [fewieden/MMM-Fuel#2]
Sine 2016-09-22 the module does not display any data and shows the following error in the log:
`Error no fuel data`

Screenshot of the module as displayed in MagicMirror:
![mmm-fuel-20160923](https://cloud.githubusercontent.com/assets/13119767/18787174/f2e1e3a0-81a1-11e6-8d09-6afaffd52658.png)

I did not change the configuration of MagicMirror, MMM-fuel or the Raspberry itself since 2016-09-19. While writing up this issue today I updated MMM-Fuel, but the issue remains.

It may be a coincidence, but there is a blogpost on the same date at the 
[tankerkoenig blog](http://blog.tankerkoenig.de/2016/09/bitte-nutzt-unser-freies-api.html) about using the API.

**Comment by fewieden** [comment]
Hmm for me it's still working. The error message should come up, if you get a response with statuscode 200, but the ok property in the json response is not true. Did you try to request the URL in the browser, maybe your API key got suspended. https://creativecommons.tankerkoenig.de/json/list.php?lat=52.518611&lng=13.408333&rad=5&type=diesel&apikey=APIKEY&sort=dist do you receive some data?

**Comment by der-test** [comment]
You are right, my API key got suspended. I will contact tankerkoenig to get the suspension removed.

**Comment by fewieden** [comment]
Take a look in their terms of use there are restrictions for smart mirrors, I will increase the defaults and add a notice to readme
