### ISSUE TITLE
Rounded prices

### ISSUE THREAD

**Issue by matthes0815** [fewieden/MMM-Fuel#21]
Platform (Hardware/OS):

Node version:
6.10.2
MagicMirror version:
latest
Module version:
latest
Description of the issue:
The prices are rounded to two decimal places since a few days.

**Comment by fewieden** [comment]
Hi @matthes0815, this came with the latest update, I might revert it to be configurable in the next days

**Comment by fewieden** [comment]
https://github.com/fewieden/MMM-Fuel/releases/tag/v.1.1.1
