### ISSUE TITLE
Error no fuel data

### ISSUE THREAD

**Issue by micherlinman** [fewieden/MMM-Fuel#23]
Platform (Hardware/OS):
Raspberry Pi 3 Linux raspberrypi 4.4.11-v7+

Node version:
v6.10.3

MagicMirror version:
yesterday installed

Module version:
v1.1.1

Description of the issue:
I copied the Repo to my Modules folder, installed 

> npm install --productive

in the MMM-Fuel folder and my config file is nearly a copy of the example:
`
{
    module: "MMM-Fuel",

    position: "top_right",

    config: {

        api_key: "6f1c9296-2ae3-0c9f-d26f-9043587c61c5",

        lat: 52.518611,

        lng: 13.408333,

        types: ["diesel"]

    }

},`

but everytime I get the Error "Error no fuel data".
How to fix?

**Comment by micherlinman** [comment]
it was my mistake, i forgot to enable the api code. After enabling I got this error while starting:
`Whoops! There was an uncaught exception...
TypeError: Cannot read property 'statusCode' of undefined
    at Request.request [as _callback] (/home/pi/MagicMirror/modules/MMM-Fuel/apis/tankerkoenig.js:115:29)
    at self.callback (/home/pi/MagicMirror/modules/MMM-Fuel/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/pi/MagicMirror/modules/MMM-Fuel/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
MMM-Formula1 received a notification: CONFIG
MMM-Formula1 is fetching driver standings
Make request: /api/f1/current/driverStandings.json (GET)
Whoops! There was an uncaught exception...
{ Error: getaddrinfo ENOTFOUND ergast.com ergast.com:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'ergast.com',
  host: 'ergast.com',
  port: 80 }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
fatal: unable to access 'https://github.com/MichMich/MagicMirror.git/': Could not resolve host: github.com
`

I removed the if else case " if (response.statusCode === 200) {" , so now it works

**Comment by der-test** [comment]
@micherlinman You may want to remove your API code from your post. Otherwise it may be used by someone else and get blocked.
