### ISSUE TITLE
MMM-Fuel Modul zeigt falsche Tankstellen an

### ISSUE THREAD

**Issue by CaptainF** [fewieden/MMM-Fuel#28]
Platform (Hardware/OS):pi3

Node version:?

MagicMirror version:2

Module version:MMM-Fuel

Description of the issue:
<h1>Hallo Zusammen,</h1>

bin absoluter Neuling! Ich habe das Modul MMM-Fuel installiert und es wird auch alles angezeigt. Nur nicht meine Tankstellen (Magdeburg), sondern welche aus Berlin. API Key habe ich eingegeben, Koordinaten sind mit drin... ich habe keine Ahnung woran es liegen könnte!!
```

{
module: "MMM-Fuel",
position: "lower_third",
config: {
api_key:"xxxxxxxxxxxxxxxxxxxxxxxx",
lat: 52.520999,
lng: 13.438038,
types: ["diesel"],
radius: 5,
updateInterval: 900000,
}
},

```
Danke schon vorab für eure Hilfe!!!

**Comment by fewieden** [comment]
I will take a look later this week/weekend
