### ISSUE TITLE
Module not shown on screen

### ISSUE THREAD

**Issue by Jonathan214** [fewieden/MMM-Fuel#30]
Hello, same problem here, i got this config:

{
module: "MMM-Fuel",
position: "bottom_right",
config: {
api_key: "d74db2a1-54af-9ef9-7eef-bb61c77a30b2",
lat: 53.050241,
lng: 8.646684499999992,
types: ["diesel"]
}
},

with the Key i got from "Tankerkoenig" and the Screen is black but I don't get any errors.
I installed "request".
@raspberrypi:~ $ node -v
v6.13.0
pi@raspberrypi:~ $ npm -v
3.10.10

is there anything else i should check?

**Comment by Jonathan214** [comment]
I got the issue, when you download this file the folder name is "MMM-Fuel-master" and it needs to be
"MMM-Fuel". I Leave this open so you can see and maybe change it

**Comment by fewieden** [comment]
The problem is you downloaded the project and didn't clone it, github adds -master (the branch name) at the end
