### ISSUE TITLE
Radius option ignored when provider spritpreisrechner selected

### ISSUE THREAD

**Issue by schiegg** [fewieden/MMM-Fuel#31]
Platform (Hardware/OS): Docker container on Ubuntu 16.04 LTS
Node version: latest (02.06.2018)
MagicMirror version: latest (02.06.2018)
Module version: latest (02.06.2018)

**Description of the issue:** When provider: "spritpreisrechner" is selected, the module shows gas stations over 12km away although radius option is set to 7. In a 7km radius there would be other gas stations available that are more expensive. Thanks for your help, the module is great!

**Comment by fewieden** [comment]
It's a year ago I did this. I remember `spritpreisrechner` doesn't provide a radius option like `tankerkoenig`, that's why I had to do kind of a custom solution with creating a square/rectangle.

Can you provide your Config without api key, so i can have a look?

**Comment by schiegg** [comment]
Im near the border to austria so i just want to get the prices of the two gas stations that are really close to me just to decide if its profitable to drive the 6km more.

I got an api key for `tankerkoenig` but i didnt need it in this configuration, do I? Here is what I copied out of my config.js (changed the lat/long a bit for privacy reasons):

`{ module: "MMM-Fuel", position: "top_right", config: { provider: "spritpreisrechner", lat: 48.569398, lng: 13.454522, types: ["e5"], sortBy: "e5", radius: 4, max: 2, rotate: false, }, },`

**Comment by fewieden** [comment]
Yes, spritpreisrechner doesn't need an api key only tankerkoenig. Spritpreisrechner has maintainance right now :/ Why do you have radius 4km in the config, but in your first message you said 7km radius?

**Comment by schiegg** [comment]
It was a mistake, I have to drive approximatly 6-7km more to get to the austrian gas station, so the radius is 3-4km.

**Comment by fewieden** [comment]
I just saw that they have a proper API https://api.e-control.at/sprit/1.0/doc/public. I will see if I can implement that one soon and get rid of the old one. Can you tell me which gas stations you would expect to be displayed and which are actually displayed. So I have a reference when I'm implementing the new version.

**Comment by schiegg** [comment]
And a new modern web design 👍  
Right now the module doenst work, maybe because of the API change?
It displayed the BP in Schärding and Diskont Lichtenauer in Münzkirchen, but I would like to get information about Turmöl in Freinberg and Freie Avia Tankstelle in Schardenberg.

**Comment by schiegg** [comment]
Im so sorry @fewieden... Its embarassing but I made a terrible mistake with the distances... you were right: 6-7km to the gas stations (radius). Good that Im no geographer 🙈 

This explanation makes sense. Like you predicted it shows the AVIA but not the Turmöl station (the cheaper one most of the time). The gas stations at the border arent the cheapest, no results will be the case often then.

**Comment by fewieden** [comment]
Did you try my new version?

I tried to set the gps coordinates more to the north west in germany, in the hope that it might return less than 10 stations because they could use an internal max radius option, but no luck.

**Comment by schiegg** [comment]
Sry for the late reply, my car got an serious oil problem and I had to look for a new one...

Yes I pulled the debug branch and now sometimes the AVIA pops up but usually it shows no stations.

Too bad :/ Would have been a simple solution... Any other ideas?

**Comment by fewieden** [comment]
No unless e-control supports querying with a radius, some sort what the old api supported

**Comment by schiegg** [comment]
What if we take the value of the most expensive gas station and write a ">" before this value for all gas stations not providing a value after the radius filter applied? So there would be a value and at least a bit information..

**Comment by fewieden** [comment]
You can `git pull` for the new version
