### ISSUE TITLE
&#8230 in all strings

### ISSUE THREAD

**Issue by Kugelfang666** [fewieden/MMM-Fuel#36]
Platform (Hardware/OS):
      Raspberry Pi 3
MagicMirror version:
      latest
Module version:
      2.0
Description of the issue:

on the screen all lines are terminated with "&#8230". It appears that something is wrong with the strings

it looks like this:
```
 DUESSELDORF, KOELNER LAN&#8230;
 40591 DUESSELDORF - KOEL&#8230;
```

with previous versions I didn't have this problem. could it be that this behavior is introduced since 2.0?

**Comment by fewieden** [comment]
Could be, for some reason it cannot render the ellipsis in your MagicMirror.

**Comment by Kugelfang666** [comment]
Thanks for looking I to this. What i don’t understand is why there is an ellipsis in the middle of a word

**Comment by rabbit83ka** [comment]
I can confirm this, same behavior here (also a Pi3 with latest Magic Mirror and MMM-Fuel module).

**Comment by fewieden** [comment]
I can only produce this issue with the config option `shortenText: 24` active. For the full text, there is no ellipsis.

**Comment by fewieden** [comment]
I applied now a fix to the develop branch, please try and test it.

```
cd ~/MagicMirror/modules/MMM-Fuel
git checkout develop
git pull
cd ~/MagicMirror
npm start dev
```

**Comment by rabbit83ka** [comment]
The fix works. Thanks!

**Comment by Kugelfang666** [comment]
I can confirm also works for me! Thanks a lot for looking into this
