### ISSUE TITLE
UpdateInterval shorter than 15 minutes causes ECONNREFUSED api response

### ISSUE THREAD

**Issue by sdetweil** [fewieden/MMM-Fuel#38]
Platform (Hardware/OS):

Node version:

MagicMirror version:
2.9
Module version:

Description of the issue:
set the UpdateInterval to 360000 (6 minutes in Milliseconds)

after a few cycles the api will fail (and not recover) with error  ECONNREFUSED

**Comment by fewieden** [comment]
This issue is mentioned in the readme https://github.com/fewieden/MMM-Fuel#tankerkoenig-germany-only I also added it now to the config option specifically https://github.com/fewieden/MMM-Fuel/pull/42
