### ISSUE TITLE
show more than 1 type of gas

### ISSUE THREAD

**Issue by ostfilinchen** [fewieden/MMM-Fuel#4]
[MMM-Fuel.zip](https://github.com/fewieden/MMM-Fuel/files/522366/MMM-Fuel.zip)
here the file for Change to the original

**Comment by ostfilinchen** [comment]
file:///home/pi/MagicMirror/modules/MMM-Fuel/MMM-Fuel.js

i have change this file again, to show if the gas station is open or not. you can enable this with the parameter "open" set to true in the config.js.

**Comment by fewieden** [comment]
will check this out, but two other modules will have a higher priority first

**Comment by ostfilinchen** [comment]
no Problem - i've a script, that works for me :-)
