### ISSUE TITLE
Feature Request: Add support for USA

### ISSUE THREAD

**Issue by Colemata** [fewieden/MMM-Fuel#45]
It would be amazing to add support for USA! ❤️

**Comment by fewieden** [comment]
Hi @Colemata, thanks for your interest in this module. Unfortunately, I didn't find a nice API for prices in the USA. If you can find one feel free to send a pull request with a new API provider implemented in the module.

Refer to https://github.com/fewieden/MMM-Fuel/tree/master/apis

**Comment by fewieden** [comment]
@Colemata I just released the new version 2.3.0 with support for USA
