### ISSUE TITLE
add suport for USA

### ISSUE THREAD

**Issue by MemBoi** [fewieden/MMM-Fuel#52]
Platform (Hardware/OS):

Node version:

MagicMirror version:

Module version:

Description of the issue:

**Comment by fewieden** [comment]
@MemBoi do you know about a free public API that provides the data you are asking for?

**Comment by fewieden** [comment]
Duplicate of https://github.com/fewieden/MMM-Fuel/issues/45#issuecomment-625439806

**Comment by fewieden** [comment]
@MemBoi I just released the new version 2.3.0 with support for USA
