### ISSUE TITLE
Feature? Show specific Gas Stations

### ISSUE THREAD

**Issue by TheStormbringer** [fewieden/MMM-Fuel#53]
Hey guys,

I was wondering whether there could be an option to show _specific_ gas-stations instead of all gas stations within a radius based around static coordinates?
I was playing around with the tankerkoenig API-Map and found out that indeed every station has its own ID, but I've been (yet) unable to implement or modify the module accordingly as I am still new to this project.

The reason of my request is quite simple: There are several (maybe around 6) gas-stations that are on my 25km/15mi way to work and I would love to identify the best price before departing. When I am using a 25km/15mi radius based upon my home-address, my work-address or even a fictional address somewhere half-way, there still will be some >20 stations, and those shown on my mirror (sorted by name or price) are usually not in my interest as they are not on my route.

I think this feature might come in handy for everyone that uses a company-car with a fueling-contract, too. Usually those contracts are limited to certain gas stations or station-brands, so it would be very useful in those cases to show only specific/static stations maybe...?

**Comment by fewieden** [comment]
@TheStormbringer in the meantime it is possible for the tankerkoenig API to request 10 specific station IDs.

A pull request should provide the possibility to use both functionalities: Radius search and ID search.

**Comment by TheStormbringer** [comment]
> @TheStormbringer in the meantime it is possible for the tankerkoenig API to request 10 specific station IDs.
> 
Hey @fewieden,
I would like to excuse myself for a rather stupid question :/ Do you mean that tankerkoenig added the feature that 10 specific IDs can now be requested through their API, or that the module MMM-Fuel now offers an option to request 10 IDs?

**Comment by fewieden** [comment]
@TheStormbringer the functionality only exists on the API level. There was an attempt of a user to integrate it into the module, but it was never finished.

**Comment by TheDuffman85** [comment]
Hi. I performet a pull request which covers this feature. See PR #57.

**Comment by fewieden** [comment]
@TheStormbringer this was implemented a while ago, see config options for [tankerkönig](https://github.com/fewieden/MMM-Fuel#tankerkoenig-germany-only).
