### ISSUE TITLE
no Stations shown for Austri/Vienna

### ISSUE THREAD

**Issue by sommer05** [fewieden/MMM-Fuel#54]
when i try to get petrol stations for austria, with this config.js
		{
			module: "MMM-Fuel",
			position: "left",
			config: {
					lat: 48.114043,
				    lng: 16.282099,
					types: ["e5"],
        			}
				},
i'm still get "Lade..." line, but no data

if i use an api key and coordinates for germany - i get some.
so module seems to run ok in germany but not for austria 
seems to be some api key issue
what to do ?
thx

**Comment by sommer05** [comment]
found the solution by myself (for sure after writing this issue):
instead of spritkoenig you have to put in spritpreisrechenr in the "provider" field.
description is in my opinon not quite clear...
thx

**Comment by fewieden** [comment]
@sommer05 do you think it is now clearer as before? I added the provider details into the specific section as well.

https://github.com/fewieden/MMM-Fuel#spritpreisrechner-austria-only
