### ISSUE TITLE
No data when using stationIds

### ISSUE THREAD

**Issue by waldmeisterx** [fewieden/MMM-Fuel#60]
Platform (Hardware/OS): 

Node version: 

MagicMirror version: 2.15.0

Module version: 2.2.0

Description of the issue:
Very happy to find new option of using stationIds instead of radius and max.
After adding stationIds with one or two stations there are no stations showing up, only "Lade..."

This is my module config:

```
{
	module: "MMM-Fuel",
	position: "top_right",
	classes: "medium",
	config: {
		api_key: "MY-API-KEY",
		lat: x.xxx,
		lng: y.yyy,
		types: ["diesel"],
		showOpenOnly: true,
		showAddress: false,
		shortenText: 20,
		rotate: false,
		sortBy: "diesel",
		updateInterval: 1800000,	// 30 min
		stationIds: [
			"e1a15081-2552-9107-e040-0b0a3dfe563c",
			"51d4b59a-a095-1aa0-e100-80009459e03a"
		],
		//radius: 1,
		//max: 2,
	}
},

```
Running this config I found following lines in debug.log

```
[07.04.2021 22:22.37.236] [LOG]   Error: Error no fuel station prices
    at getPricesByStationList (/home/pi/MagicMirror/modules/MMM-Fuel/apis/tankerkoenig.js:247:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.getData (/home/pi/MagicMirror/modules/MMM-Fuel/apis/tankerkoenig.js:279:36)
    at async Class.getData (/home/pi/MagicMirror/modules/MMM-Fuel/node_helper.js:84:26)
...later...
[07.04.2021 22:43.14.930] [LOG]   Error: Error no fuel station prices
    at getPricesByStationList (/home/pi/MagicMirror/modules/MMM-Fuel/apis/tankerkoenig.js:247:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.getData (/home/pi/MagicMirror/modules/MMM-Fuel/apis/tankerkoenig.js:279:36)
    at async Class.getData (/home/pi/MagicMirror/modules/MMM-Fuel/node_helper.js:84:26)

```

Changing back same config to radius and max instead of stationIds it shows up the data.

**Comment by fewieden** [comment]
@waldmeisterx since you removed your coordinates I can only guess what could be wrong. I assume you were running into the same issue as the user in the forum https://forum.magicmirror.builders/post/90310.

If your stations are included in the default radius of 5km then there is currently an [issue](https://github.com/fewieden/MMM-Fuel/pull/59#issuecomment-813537136) that we are going to solve. If you only care for those two stations you can set the radius to 0 (will disable the radius search) to make it work

**Comment by fewieden** [comment]
@waldmeisterx I just released a new version of this module which should fix the issue I described.

**Comment by waldmeisterx** [comment]
> @waldmeisterx I just released a new version of this module which should fix the issue I described.

OK, thanks for the fast reply.
In MY real config there are real coordinates.

First, I tested the workaround (added radius: 0 to the config) and this one works.

This moment I saw release 2.2.1 and tried this one too (and removed radius: 0 again).
Result: I see 5 (open) fuel stations, instead of 1 (of my two configured, one is closed now!)
So it does not only select the configured Ids. 
If I'm going to add radius: 0 again, it is like the first workaround.

**Comment by fewieden** [comment]
@waldmeisterx if you only care about the two specified stations it is intended to set the radius to 0. Otherwise, it will fetch the default of 5km. See description of radius for provider tankerkoenig `Valid range is 0-25. Set to 0 to disable. Not required if stationIds are provided.`  in the [readme](https://github.com/fewieden/MMM-Fuel#tankerkoenig-germany-only)

The reasoning behind this is that users want to be able to use both options at the same time. E.g. I want to see the fuel prices in a radius of 5km to my home address including two stations I pass along the way to work.

**Comment by waldmeisterx** [comment]
@fewieden ok, I understand. I set radius: 0 and see only my two stations, but...

It seems that these two entries do not update their prices. Both are fix at 1.349 EUR.
My smarthome polls the same two stations and the prices have changed several times today.
Might there be a (new) problem with updating the data?

**Comment by fewieden** [comment]
@waldmeisterx can you please give some more details that might help to investigate the issue?

- Does your smarthome also use the tankerkoenig API?
- Does the mirror update it at one point?
- Can you see error logs in the console?
- If the issue appears and you restart the mirror does it fetch the correct price or is it still outdated?

**Comment by waldmeisterx** [comment]
@fewieden sure, no problem

I use home assistant (HA) as smart home and there is an integrated module for tankerkoenig, but it's written in python I think.
Here you can find the details https://github.com/home-assistant/core/tree/dev/homeassistant/components/tankerkoenig
(sorry, I'm not good in js or python, but maybe the code will help you).

I think, the HA component also uses the same tankerkoenig API. I use the same key for both (at the same time).
At start of MM it updates the price to the current.
![MMM-Fuel1](https://user-images.githubusercontent.com/2168391/114318151-fc9c9d80-9b0b-11eb-9fe1-6ca6a774325c.jpg)
There is only this info in the debug output:
`[11.04.2021 21:24.26.697] [LOG]   Starting module helper: MMM-Fuel`
Currently I've integrated the HA data with MMM-homeassistant-sensors to MM, so I only need to read the data via API once (with HA).

Now I wait for the next update interval (30+ min.) and give you more updates as requested.
Do I need to set special parameters for more detailed output?

**Comment by waldmeisterx** [comment]
This morning it seems to be ok, the values are the same
![image](https://user-images.githubusercontent.com/2168391/114354645-cc3a1b00-9b6e-11eb-8920-50b001e9a039.png)

I can't find any entries in the debug log.
So I don't know if it is necessary to do more investigations for it?
If you don't think so, I'm going to close this issue.

**Comment by fewieden** [comment]
@waldmeisterx I would surveil the module a bit until it appears again.

- Did you see the module ever updating the price to something different than on initialization?
- The module updates every 30min. How frequently does your homesassistant update?

There is currently no option for more detailed logs.

**Comment by waldmeisterx** [comment]
@fewieden 
- yes, the module does price updates differenz from initialization
- HA updates prices every 5 mins
Currently, in addition I have included the HA tankerkoenig data with the MMM-homeassistant-sensors module from HA, which also provides custom naming and an station logo.

**Comment by fewieden** [comment]
@waldmeisterx If the module updates in general, then it sounds more like a temporary hiccup or the difference between the 5min and 30min update interval to your home automation.

Feel free to reopen the ticket when this occurs again.

**Comment by waldmeisterx** [comment]
closed.
