### ISSUE TITLE
update MMM-Fuel

### ISSUE THREAD

**Issue by lexnared** [fewieden/MMM-Fuel#62]
Platform (Hardware/OS): Raspbbery Pi 3b+

Node version: v10.15.0

MagicMirror version: 2.11.0

Module version:

Description of the issue:

what do i have to do for an update MMM-FUEL?

**Comment by lexnared** [comment]
> Platform (Hardware/OS):
> 
> Node version: v10.15.0
> 
> MagicMirror version: 2.11.0
> 
> Module version:
> 
> Description of the issue:
> 
> what do i have to do for an update MMM-FUEL?

**Comment by fewieden** [comment]
@lexnared you would open a terminal and go to the module directory. In most cases, this would be `cd ~/MagicMirror/modules/MMM-Fuel`.

Then you have to pull the newest version from git `git pull`.

To ensure you have all dependencies installed run `npm i --production`.

After that you can change the config and restart the mirror.

**Comment by lexnared** [comment]
Okay, thanks 👍🏼
