### ISSUE TITLE
Only displays "undefinded"

### ISSUE THREAD

**Issue by burberius** [fewieden/MMM-Fuel#63]
Platform (Hardware/OS): Raspberry

Node version: v10.24.0

MagicMirror version: current

Module version: current

Description of the issue:

Instead of the content of the module it just shows "undefined". I didn't use the display for a few weeks now and after starting it up now the fuel module just shows "undefined" after data is returned from the API.
When I open the "page" of the magic mirror via the browser it is displayed properly as before. It just happens on the display of the mirror.
Is there any way I can debug this?

**Comment by burberius** [comment]
I checked out previous versions and 2.1.2 works without problems.

The first station is named OIL! could that be a problem?

**Comment by fewieden** [comment]
@burberius I don't think the name of the station should influence this. Can you please also post your config of the module? Make sure to remove the API key.

Since it is working if you open the page on the browser I expect it to be a rendering issue inside of electron. You can check the logs in the developer console for errors. To open DevTools, use the shortcut "Ctrl+Shift+I" or the <F12> key.

PS: Node 10 has reached the end of life, you should consider updating it https://endoflife.date/nodejs

**Comment by burberius** [comment]
```
               {
                        module: "MMM-Fuel",
                        position: "top_right",
                        config: {
                                api_key: "451xxxxxxxxxxxxxxxxxx3738b",
                                lat: 51.3511798,
                                lng: 12.3743467,
                                types: ["e5"],
                                sortBy: "e5",
                                showOpenOnly: true,
                                showAddress: false,
                                shortenText: 25
                        }
                },
```

Console log doesn't show any errors!

I'll try to find out the problem by applying the single commits.

**Comment by burberius** [comment]
I narrowed the problem down to commit 61d2ece5c6cbdfd7a90692b2b32ad5f3097844b9
The previous one works fine, this one breaks it.
To eliminate the node version I also upgraded to v16.0.0

**Comment by fewieden** [comment]
@burberius I just checked out the newest version of the module with the `develop` branch of MagicMirror. I entered your config and for me, the module is displaying fine.

Are you using electron on the Mirror?

![image](https://user-images.githubusercontent.com/9334168/116827726-db731e00-ab9a-11eb-9e9a-a2765608b3cc.png)

Looking at the commit that introduced the issue for you, I could imagine that the problematic part is the Intl object. But it is supported by Chrome and therefore electron. If you would use the Midori browser, as some people do with the pi 0, it doesn't support ES6. However, then I still would expect an error in the console.

https://caniuse.com/mdn-javascript_builtins_intl_numberformat_format
https://caniuse.com/mdn-javascript_builtins_intl_numberformat_formattoparts

**Comment by burberius** [comment]
I use the default installation of MagicMirror, so I guess it's electron.

Is there a way to see it's logs/console?

**Comment by burberius** [comment]
Another thing I recognized is, I don't have to restart MM to trigger the problem. When I have to brocken commit checked out the "undefined" occures on the next reload.
And also when I change back it gets fine. Perhaps that helps.

**Comment by burberius** [comment]
After trying different stuff I could narrow it down to the formatDistance method.
I then found that I really didn't have the latest version of MM. I thought it will always display a message at the top if it is outdated.
After updating it and taking the master version of MMM-Fuel it is now displayed as normal.
Sorry for the fuss!
