### ISSUE TITLE
Fading Brightness like the Calendar items

### ISSUE THREAD

**Issue by Dom1n1c** [fewieden/MMM-Fuel#7]
To have a clearer layout.

**Comment by Sennahoj82** [comment]
I share this view.
It would be wonderful if the module would get a fading option.

**Comment by fewieden** [comment]
https://github.com/fewieden/MMM-Fuel/projects/1

**Comment by fewieden** [comment]
@Dom1n1c @Sennahoj82 in case you are still using this module I just implemented fading brightness. To check it out until it is released you can run the following commands.

```bash
cd ~/MagicMirror/modules/MMM-Fuel
git checkout develop
git pull
npm i --production
```

**Comment by fewieden** [comment]
@Dom1n1c @Sennahoj82 I just released the new version with the fading config option
