### ISSUE TITLE
CERT_HAS_EXPIRED

### ISSUE THREAD

**Issue by KopiTubruk** [fewieden/MMM-Fuel#77]
Platform (Hardware/OS): Rasperian

Node version: newest

MagicMirror version: newest

Module version: newest

Description of the issue:

I can't get any prices from tankekoenig. Fetches data ends up with: FetchError: request to https://creativecommons.tankerkoenig.de/json/list.php?lat=<private>&lng=<private>&rad=15&type=all&apikey=xxxxxx-xxxx-x-xxxxxx-xxx&sort=dist failed, reason: certificate has expired

Is it an issue of MMM_Fuel? What can I do to get it working?

**Comment by mazim-co** [comment]
Same here. Even with a new API it doesn't work anymore.

**Comment by fewieden** [comment]
@KopiTubruk @mazim-co this is caused by the expiration of a root certificate from lets encrypt https://twitter.com/letsencrypt/status/1443621997288767491

You should get the latest MagicMirror release to fix it https://github.com/MichMich/MagicMirror/releases/tag/v2.17.1

**Comment by Quarx64** [comment]
@Softyathome 
Add the line
process.env.NODE_TLS_REJECT_UNAUTHORIZED;
above
const BASE_URL = 'https://creativecommons.tankerkoenig.de/json';
and change
const BASE_URL = 'https://creativecommons.tankerkoenig.de/json';
to
const BASE_URL = 'http://creativecommons.tankerkoenig.de/json';
in apis/tankerkoenig.js

**Comment by Softyathome** [comment]
Hi Quarx64,
thanks for your reply, but this won't work for me - still just "Load" to see after
pm2 restart mm

Here the part out of the tankerkoenig.js
*** SNIP ***********************************************************
/**
 * @external geolib
 * @see https://www.npmjs.com/package/geolib
 */
const geolib = require('geolib');

process.env.NODE_TLS_REJECT_UNAUTHORIZED;
const BASE_URL = 'http://creativecommons.tankerkoenig.de/json';

let config;
let stationInfos;
*** SNAP ***********************************************************

Any ideas?
Thanks

**Comment by Pika106** [comment]
> There is no need to modify the module files. As mentioned before:
> 
> > @KopiTubruk @mazim-co this is caused by the expiration of a root certificate from lets encrypt https://twitter.com/letsencrypt/status/1443621997288767491
> > You should get the latest MagicMirror release to fix it https://github.com/MichMich/MagicMirror/releases/tag/v2.17.1
> 
> I just tested it, please make sure you use the newest version of MagicMirror + dependencies to contain the fix [MichMich/MagicMirror#2674](https://github.com/MichMich/MagicMirror/pull/2674)
> 
> ![fuel](https://user-images.githubusercontent.com/9334168/137770363-49611c8b-7dc7-4033-a47f-0a61a2d6e2f3.png)

Doesn´t work for me.... Set up a complete new system and it won´t load the stations....
...edited the tankerkoenig.js and the same problem here

"electron": "^13.5.1"

"name": "magicmirror",
"version": "2.17.1",

**Comment by Softyathome** [comment]
On a PI4 i've installed everything new.
Update node to version 17 and then with the script from sdetweil the basic MM (2.18) install.
After that i've tried MMM-Fuel (with my api, and lat. etc.), ending  with "loading" on my MM.
I've fixed that with npm install geolib.
After that MMM-Fuel works as befor.
Greets
Jens

**Comment by fewieden** [comment]
@Softyathome running `npm install geolib` shouldn't be required. It is part of the package.json file. If you follow the installation instructions of the module it should already be downloaded.
