### ISSUE TITLE
Module not running

### ISSUE THREAD

**Issue by tk273** [fewieden/MMM-Fuel#78]
Platform (Hardware/OS): Pi 3/Raspios 21/10/30

Node version:

MagicMirror version: 3.2

Module version: actually/install for one week

Description of the issue:
The Modul is not running. Where is the Problem, when to paste "shortenText" comes Mirror error, when to paste "stationsIds" comes Mirror error, when delete the second line (stationID + shortenText) than work the modul. Can you help me? Did I forgot something?
 
{
                        module: "MMM-Fuel",
                        position: "top_left",
                        config: {
                        api_key: "xxx-xxx-xxx-xxxx-xxxxx",
                        lat: 50.980031,
                        lng: 11.895965,
                        types: ["diesel", "e5"],
                        radius: 0
                        shortenText: false
                        stationIds:     [bf3b5e44-250f-40ac-a826-629984d647fb],
                                        [341a80d7-e0f8-483b-8d34-aea307fa9605],
                        // all your config options, which are different than th$
                }
                },

**Comment by fewieden** [comment]
@tk273 you have a couple of syntax issues here.

-  Every config option should have a comma at the end, e.g.

```js
radius: 0,
shortenText: false,
```

- Strings have to be surrounded by single or double quotes, e.g.

```js
stationIds: ["bf3b5e44-250f-40ac-a826-629984d647fb"],
```

- One-dimensional arrays should have their items comma-separated and within one pair of square brackets, e.g.

```js
stationIds: ["bf3b5e44-250f-40ac-a826-629984d647fb", "341a80d7-e0f8-483b-8d34-aea307fa9605"],
```

You could also run the command `npm run config:check` in the MagicMirror project to check your config for most syntax issues.

The correct config would look like this:

```js
{
	module: "MMM-Fuel",
	position: "top_left",
	config: {
		api_key: "xxx-xxx-xxx-xxxx-xxxxx",
		lat: 50.980031,
		lng: 11.895965,
		types: ["diesel", "e5"],
		radius: 0,
		shortenText: false,
		stationIds: ["bf3b5e44-250f-40ac-a826-629984d647fb", "341a80d7-e0f8-483b-8d34-aea307fa9605"],
	}
},
```
