### ISSUE TITLE
Currency Format for AUD

### ISSUE THREAD

**Issue by RexFlymo** [fewieden/MMM-Fuel#86]
Is there anyway to change currency format.

The way the prices are formatted they are actually showing a price 100 times higher than it should be.

The pricing for Australia (NSW) currently shows as A$176.900

This is confusing as the pricing should be 176.9c and only be shown to one decimal places as this is how fuel prices are displayed in Australia.

**Comment by RexFlymo** [comment]
I believe this is related to the way that fuel prices are displayed in Australia. 

I think that the NSW API is returning a value of 176.9 which the module it treating as being an AUD value when it is in fact the value in cents with one decimal place. This would be due to the way that fuel prices are displayed in Australia where for some reason we don't show the price in dollars only ever in cents. You wouldn't see a fuel station display the price as $1.769 they will show it as 176.9c

**Comment by fewieden** [comment]
@RexFlymo I'm converting now the value correctly to Australian dollars in my work in progress branch develop.

![image](https://user-images.githubusercontent.com/9334168/162522064-31364c7a-4533-42b8-baed-01c94e3578e0.png)

Since I'm planning to add more changes before releasing the new version to master you probably want to switch to the develop branch in the meantime.

```
cd ~/MagicMirror/modules/MMM-Fuel
git checkout develop
git pull
npm i --production
```

**Comment by RexFlymo** [comment]
That looks great.

Thank you again for such a great module and for supporting it so well.

**Comment by RexFlymo** [comment]
Not sure why but I am getting an error when changing to the develop branch after entering git checkout develop I am getting the following error message.

error: pathspec 'develop' did not match any file(s) known to git

**Comment by RexFlymo** [comment]
Can't seem to change to the develop branch I keep getting the error "error: pathspec 'develop' did not match any file(s) known to git" when I run the git checkout develop command.
When I run git branch I only see * master.

**Comment by fewieden** [comment]
@RexFlymo try to run `git fetch` to sync the repository before `git checkout develop`

**Comment by RexFlymo** [comment]
Doesn't seem to make a difference still get the same error.

**Comment by fewieden** [comment]
@RexFlymo

- How did you change to develop before you started the complete reinstall of MagicMirror?
- How did you install the module? `git clone ...`?

There are more commands to fetch the list of remote branches:
```
git fetch --all
git fetch origin develop
```

**Comment by RexFlymo** [comment]
Now fixed.

I was being lazy when I did the reinstall and reused the git clone command from another module resulting in the following
 git clone --depth=1 https://github.com/fewieden/MMM-Fuel
I didn't notice or understand the impact of the depth = 1 option. Have now cloned it without this option using this option and everything is working as expected and I am now running the develop branch. The fuel prices are display exactly as they should now.

Thank you so much for your time and patience in helping me navigate my way through these problems.

Thank you also for two modules that I am now using on my setup MMM-Fuel and MMM-NFL both of them are giving my mirror great functionality.

**Comment by fewieden** [comment]
No worries, glad you like my modules
