### ISSUE TITLE
StationIds not working

### ISSUE THREAD

**Issue by mishu28nmv** [fewieden/MMM-Fuel#88]
Platform (Hardware/OS): Raspberry 3B+
MagicMirror version: 2.18
Module version: 2.2.1
Description of the issue: When I try to use just 3 stations with Ids and no radius, the module returns other stations. This is my config:
````
{
    module: "MMM-Fuel",
    position: "top_left",
    config: {
        provider: "tankerkoenig",
	api_key: "bla-bla-bla",
        lat: xxxx,
        lng: yyyy,
        types: ["diesel"],
	stationIds: ["e998242c-0c32-4541-a00a-e8a53ff90bae", "2bcc801e-8c9f-4559-afe0-70f2f3aed092", "a7187740-91db-4687-81d5-c9db4d5d250e"],
        rotate: false,
        showAddress: true,
        showDistance: true,
        iconHeader: true,
        updateInterval: 900000,
        // all your config options, which are different than their default values
    }
},
````
Tried out also with radius 0 or 10. Then they show, but don't update. Can someone help me?

**Comment by fewieden** [comment]
@mishu28nmv if you want only the stations from your list and no radius search you have to specifically set `radius: 0`.

Since you said you tried that already, I have to check why it is not updating.

**Comment by mishu28nmv** [comment]
I will check also today to see if the numbers change. I will write here again. Thanks

**Comment by fewieden** [comment]
@mishu28nmv does your issue still persist?

**Comment by mishu28nmv** [comment]
Yes. It is updating when I start the MM, but after that it stays like that the hole time!

**Comment by fewieden** [comment]
@mishu28nmv I was able to reproduce the issue. It seems to be related to stationIds. When I was using the radius option the same gas stations were updating.

I will be gone for a couple of days and will try then to pinpoint what the exact issue is.

**Comment by mishu28nmv** [comment]
Yes. It is working now. Thank you!

**Comment by fewieden** [comment]
@mishu28nmv I just released v2.3.1 with this fix to master so you can switch the branch back again.

**Comment by mishu28nmv** [comment]
And how can I do that? I'm not so good with coding :)

**Comment by fewieden** [comment]
@mishu28nmv you can run the previous commands but replacing the `develop` branch with `master`.

```bash
cd ~/MagicMirror/modules/MMM-Fuel
git checkout master
git pull
npm i --production
```

**Comment by mishu28nmv** [comment]
Thanks. I will do that!
