### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by Ray94520** [fewieden/MMM-Fuel#91]
Good job on the fuel module. Everything seems to be working fine
I am in the United States. So I am using ZIP Code

The only problem I'm having is separating
cheapest gas station  Regular mid grade

I wanted to separate them like this
cheapest gas station      Regular  mid grade
so there is more profound.  space between the 2

How can I do that
Ray

**Comment by fewieden** [comment]
@Ray94520 can you add a screenshot?

**Comment by Ray94520** [comment]
I'm sorry that has never worked for me
every time I try it it always says it's too big to post. I've even tried to make it smaller, but still run into the same problem. I do not know what I'm doing wrong. I've never been lucky at doing this

But for whatever reason I can't seem to space (cheapest gas station) further apart from (Regular) (mid grade)

**Comment by Ray94520** [comment]
Okay that looks exactly what I'm looking for. I'm not in town right now. So when I get home I'll give it a try and let you know.
I appreciate your help.
Ray

**Comment by fewieden** [comment]
@Ray94520 the modules usually take up 100% of the regions. Here is a good overview of all available regions https://forum.magicmirror.builders/topic/286/regions. There you can see that _bottom_center_ only takes the center part, whereas _middle_center_ is full width.

**Comment by Ray94520** [comment]
Okay will that's useful information. Thanks for the input. I will play around with those measurements and see what happens.
But I'm pretty happy with the bottom center. It seems to work for me.

Thank you for your help and input. I appreciated
Ray
