### ISSUE TITLE
Installation link missing!

### ISSUE THREAD

**Issue by xIExodusIx** [fewieden/MMM-Fuel#93]
Platform (Hardware/OS):
Raspberry Pi 3 B+ /  Raspberry PI OS (32 Bit) Bullseye
Node version:
16.15.1
MagicMirror² version:
2.19.0
Module version:

Description of the issue:
Can't find the Github link for installation. The "git clone https://github.com/...." is  not there. So installation for me is not possible:

**Comment by xIExodusIx** [comment]
Installed mmpm and after  that I installed MMM-Fuel using mmpm. 
This issue can be closed.

**Comment by fewieden** [comment]
@xIExodusIx it depends on the cloning method of your choosing, e.g. https, ssh, ...

You can get the correct link for all modules by clicking on the green code button on the repository like so:

![image](https://user-images.githubusercontent.com/9334168/174730752-e48c97f1-3a6f-4a49-b972-17f3aec6b9b8.png)
